import { test } from 'node:test'
import assert from 'node:assert/strict'
import {
  indexModelBundles,
  parseModelBundleName,
  selectModelBundle,
  type ModelBundleAsset,
} from './model-bundles'

const asset = (name: string): ModelBundleAsset => ({ name, size: 1, url: `https://example/${name}` })

test('parses faction id, version and build stamp from a bundle filename', () => {
  assert.deepEqual(parseModelBundleName('exiles-0.7.4.6-pedia20260712230210-models.zip'), {
    factionId: 'exiles',
    version: '0.7.4.6',
    timestamp: 20260712230210,
  })
})

test('parses dashed faction ids and numeric-only versions', () => {
  assert.deepEqual(parseModelBundleName('second-wave-0.15.0-pedia20260712084632-models.zip'), {
    factionId: 'second-wave',
    version: '0.15.0',
    timestamp: 20260712084632,
  })
  assert.equal(parseModelBundleName('mla-124664-pedia20260712084632-models.zip')?.version, '124664')
})

test('ignores assets that are not model bundles', () => {
  assert.equal(parseModelBundleName('mla-124664-pedia20260712084632.zip'), null) // spec zip
  assert.equal(parseModelBundleName('manifest.json'), null)
  assert.equal(indexModelBundles([asset('notes.txt')]).size, 0)
})

test('groups bundles per faction, newest build stamp first', () => {
  const byFaction = indexModelBundles([
    asset('mla-124632-pedia20260711230523-models.zip'),
    asset('mla-124664-pedia20260712084632-models.zip'),
    asset('legion-1.32.1-pedia20260712084632-models.zip'),
  ])

  assert.deepEqual(
    byFaction.get('mla')?.map((b) => b.version),
    ['124664', '124632']
  )
  assert.equal(byFaction.get('legion')?.length, 1)
})

test('prefers the bundle built from the requested version', () => {
  const byFaction = indexModelBundles([
    asset('mla-124632-pedia20260711230523-models.zip'),
    asset('mla-124664-pedia20260712084632-models.zip'),
  ])

  const selection = selectModelBundle(byFaction, 'mla', '124632')
  assert.equal(selection?.exact, true)
  assert.equal(selection?.bundle.version, '124632')
})

test('picks the newest rebuild when a version was built more than once', () => {
  const byFaction = indexModelBundles([
    asset('exiles-0.7.4.6-pedia20260712084632-models.zip'),
    asset('exiles-0.7.4.6-pedia20260712230210-models.zip'), // texture fix rebuild
  ])

  const selection = selectModelBundle(byFaction, 'exiles', '0.7.4.6')
  assert.equal(selection?.exact, true)
  assert.equal(selection?.bundle.timestamp, 20260712230210)
})

// The regression this module exists for: model bundles are regenerated by a
// manual workflow, faction data by a daily one. Every upstream release between
// regens used to strip `models` from the manifest entry, disabling the "View 3D
// Model" button on every unit of that faction.
test('falls back to the faction newest bundle when the exact version has none', () => {
  const byFaction = indexModelBundles([asset('exiles-0.7.4.6-pedia20260712230210-models.zip')])

  const selection = selectModelBundle(byFaction, 'exiles', '0.8.1')
  assert.equal(selection?.exact, false, 'must be flagged as a fallback, not an exact match')
  assert.equal(selection?.bundle.version, '0.7.4.6')
})

test('fallback uses the newest bundle by build stamp, not the largest version number', () => {
  // Upstream versioning is non-monotonic (see manifest-ordering.ts), so the
  // numerically-largest version can be an old build.
  const byFaction = indexModelBundles([
    asset('exiles-0.7.20-pedia20260614140054-models.zip'),
    asset('exiles-0.7.4.6-pedia20260712230210-models.zip'),
  ])

  assert.equal(selectModelBundle(byFaction, 'exiles', '0.8.1')?.bundle.version, '0.7.4.6')
})

test('faction id matching is case-insensitive', () => {
  const byFaction = indexModelBundles([asset('exiles-0.7.4.6-pedia20260712230210-models.zip')])
  assert.equal(selectModelBundle(byFaction, 'Exiles', '0.7.4.6')?.exact, true)
})

test('returns null when the faction has no bundles at all', () => {
  const byFaction = indexModelBundles([asset('exiles-0.7.4.6-pedia20260712230210-models.zip')])
  assert.equal(selectModelBundle(byFaction, 'replicate', '0.5'), null)
  assert.equal(selectModelBundle(new Map(), 'exiles', '0.7.4.6'), null)
})
